export const CREATOR_DI_TOKENS = {
  CREATOR_REPOSITORY: Symbol('CREATOR_REPOSITORY'),
  BRAND_REPOSITORY: Symbol('BRAND_REPOSITORY'),
  CREATOR_BRAND_REPOSITORY: Symbol('CREATOR_BRAND_REPOSITORY'),
  CREATOR_VALIDATOR_SERVICE: Symbol('CREATOR_VALIDATOR_SERVICE'),
  BRAND_VALIDATOR_SERVICE: Symbol('BRAND_VALIDATOR_SERVICE'),
} as const;

