export const SCRAPER_DI_TOKENS = {
  SCRAPER_JOB_REPOSITORY: Symbol('SCRAPER_JOB_REPOSITORY'),
  SCRAPER_ORCHESTRATOR_SERVICE: Symbol('SCRAPER_ORCHESTRATOR_SERVICE'),
  SCRAPER_QUEUE_SERVICE: Symbol('SCRAPER_QUEUE_SERVICE'),
  APIFY_SCRAPER_SERVICE: Symbol('APIFY_SCRAPER_SERVICE'),
  RAPIDAPI_SCRAPER_SERVICE: Symbol('RAPIDAPI_SCRAPER_SERVICE'),
  SELF_HOSTED_SCRAPER_SERVICE: Symbol('SELF_HOSTED_SCRAPER_SERVICE'),
} as const;

