/**
 * Dependency injection tokens for campaigns module
 */
export const CAMPAIGNS_DI_TOKENS = {
  CAMPAIGN_REPOSITORY: Symbol('CAMPAIGN_REPOSITORY'),
  CAMPAIGN_ALLOCATION_REPOSITORY: Symbol('CAMPAIGN_ALLOCATION_REPOSITORY'),
  CAMPAIGN_TRACKING_CONFIG_REPOSITORY: Symbol(
    'CAMPAIGN_TRACKING_CONFIG_REPOSITORY',
  ),
  APIFY_JOBS_QUEUE_SERVICE: Symbol('APIFY_JOBS_QUEUE_SERVICE'),
} as const;

