export const AUTH_DI_TOKENS = {
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  OAUTH_ACCOUNT_REPOSITORY: Symbol('OAUTH_ACCOUNT_REPOSITORY'),
  REFRESH_TOKEN_REPOSITORY: Symbol('REFRESH_TOKEN_REPOSITORY'),
  RESET_TOKEN_REPOSITORY: Symbol('RESET_TOKEN_REPOSITORY'),
  PASSWORD_SERVICE: Symbol('PASSWORD_SERVICE'),
  JWT_SERVICE: Symbol('JWT_SERVICE'),
  REDIS_LOCKOUT_SERVICE: Symbol('REDIS_LOCKOUT_SERVICE'),
  OAUTH_PROVIDER_SERVICE: Symbol('OAUTH_PROVIDER_SERVICE'),
  OAUTH_STATE_SERVICE: Symbol('OAUTH_STATE_SERVICE'),
  OAUTH_TOKEN_SERVICE: Symbol('OAUTH_TOKEN_SERVICE'),
  REDIS_CLIENT: Symbol('REDIS_CLIENT'),
  ROLE_SERVICE: Symbol('ROLE_SERVICE'),
} as const;

