export const SHARED_DI_TOKENS = {
  DATABASE_CONFIG: Symbol('DATABASE_CONFIG'),
  DATABASE_CLIENT: Symbol('DATABASE_CLIENT'),
  UNIT_OF_WORK: Symbol('UNIT_OF_WORK'),
  S3_CONFIG: Symbol('S3_CONFIG'),
  S3_CLIENT: Symbol('S3_CLIENT'),
  REDIS_CONFIG: Symbol('REDIS_CONFIG'),
  REDIS_CLIENT: Symbol('REDIS_CLIENT'),
  REDIS_SERVICE: Symbol('REDIS_SERVICE'),
} as const;
