export const ANALYTICS_DI_TOKENS = {
  PLATFORM_STATS_REPOSITORY: Symbol('PLATFORM_STATS_REPOSITORY'),
  ANALYTICS_REPORT_REPOSITORY: Symbol('ANALYTICS_REPORT_REPOSITORY'),
  STATISTICS_CALCULATION_REPOSITORY: Symbol('STATISTICS_CALCULATION_REPOSITORY'),
  DATA_TRANSFORMER_SERVICE: Symbol('DATA_TRANSFORMER_SERVICE'),
  METRICS_NORMALIZER_SERVICE: Symbol('METRICS_NORMALIZER_SERVICE'),
  STATISTICS_CALCULATOR_SERVICE: Symbol('STATISTICS_CALCULATOR_SERVICE'),
  ENGAGEMENT_CALCULATOR_SERVICE: Symbol('ENGAGEMENT_CALCULATOR_SERVICE'),
  TREND_ANALYZER_SERVICE: Symbol('TREND_ANALYZER_SERVICE'),
  REPORT_GENERATOR_SERVICE: Symbol('REPORT_GENERATOR_SERVICE'),
} as const;

